"""
Base Notification Interface for {strategy_name}
Generated by CBT Framework

Abstract base class for notification channels.
"""

from abc import ABC, abstractmethod
from datetime import datetime


class BaseNotifier(ABC):
    """Abstract notification interface."""

    @abstractmethod
    def send(self, message: str, level: str = 'info') -> bool:
        """
        Send a notification.

        Args:
            message: The message to send
            level: 'info', 'warning', 'critical'

        Returns:
            True if sent successfully
        """
        pass

    def format_message(self, message: str, level: str = 'info') -> str:
        """Format message with timestamp and level indicator."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        level_icons = {
            'info': 'ℹ️',
            'warning': '⚠️',
            'critical': '🚨',
        }
        icon = level_icons.get(level, 'ℹ️')
        return f"{icon} [{timestamp}]\n{message}"
