"""
Discord Notification Channel for {strategy_name}
Generated by CBT Framework

Sends notifications via Discord webhook.
Setup: Create a webhook in Discord channel settings → copy URL → set DISCORD_WEBHOOK_URL in .env
"""

import os
import requests
import logging
from .base import BaseNotifier

logger = logging.getLogger(__name__)


class DiscordNotifier(BaseNotifier):
    """Send notifications via Discord webhook."""

    def __init__(self):
        self.webhook_url = os.getenv('DISCORD_WEBHOOK_URL')
        if not self.webhook_url:
            logger.warning("DISCORD_WEBHOOK_URL not set in .env")

    def send(self, message: str, level: str = 'info') -> bool:
        """Send message to Discord channel."""
        if not self.webhook_url:
            return False

        try:
            formatted = self.format_message(message, level)

            # Discord color codes
            colors = {
                'info': 3447003,      # Blue
                'warning': 16776960,  # Yellow
                'critical': 15158332, # Red
            }

            payload = {
                'embeds': [{
                    'description': formatted,
                    'color': colors.get(level, 3447003),
                }]
            }

            response = requests.post(
                self.webhook_url,
                json=payload,
                timeout=10
            )

            if response.status_code in (200, 204):
                return True
            else:
                logger.error(f"Discord webhook error: {response.status_code}")
                return False

        except Exception as e:
            logger.error(f"Discord notification failed: {e}")
            return False
