"""
Email Notification Channel for {strategy_name}
Generated by CBT Framework

Sends email notifications via SMTP.
Setup: Configure SMTP credentials in .env (works with Gmail, Outlook, etc.)
"""

import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from .base import BaseNotifier

logger = logging.getLogger(__name__)


class EmailNotifier(BaseNotifier):
    """Send notifications via email (SMTP)."""

    def __init__(self):
        self.smtp_host = os.getenv('EMAIL_SMTP_HOST', 'smtp.gmail.com')
        self.smtp_port = int(os.getenv('EMAIL_SMTP_PORT', '587'))
        self.username = os.getenv('EMAIL_USER')
        self.password = os.getenv('EMAIL_PASS')
        self.to_email = os.getenv('EMAIL_TO')

        if not all([self.username, self.password, self.to_email]):
            logger.warning("Email credentials not fully set in .env")

    def send(self, message: str, level: str = 'info') -> bool:
        """Send email notification."""
        if not all([self.username, self.password, self.to_email]):
            return False

        # Only send emails for warnings and critical (avoid inbox spam)
        if level == 'info':
            return True

        try:
            formatted = self.format_message(message, level)

            subject_prefix = {
                'info': '[Bot Info]',
                'warning': '[Bot Warning]',
                'critical': '[Bot CRITICAL]',
            }

            msg = MIMEMultipart()
            msg['From'] = self.username
            msg['To'] = self.to_email
            msg['Subject'] = f"{subject_prefix.get(level, '[Bot]')} Trading Alert"

            msg.attach(MIMEText(formatted, 'plain'))

            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)

            return True

        except Exception as e:
            logger.error(f"Email notification failed: {e}")
            return False
