"""
SMS Notification Channel for {strategy_name}
Generated by CBT Framework

Sends SMS notifications via Twilio.
Setup: Create Twilio account → get SID, token, phone number → set in .env
"""

import os
import requests
import logging
from .base import BaseNotifier

logger = logging.getLogger(__name__)


class SMSNotifier(BaseNotifier):
    """Send notifications via Twilio SMS."""

    def __init__(self):
        self.account_sid = os.getenv('TWILIO_SID')
        self.auth_token = os.getenv('TWILIO_TOKEN')
        self.from_number = os.getenv('TWILIO_FROM')
        self.to_number = os.getenv('TWILIO_TO')

        if not all([self.account_sid, self.auth_token, self.from_number, self.to_number]):
            logger.warning("Twilio credentials not fully set in .env")

    def send(self, message: str, level: str = 'info') -> bool:
        """Send SMS via Twilio."""
        if not all([self.account_sid, self.auth_token, self.from_number, self.to_number]):
            return False

        # Only send SMS for warnings and critical alerts (avoid spam)
        if level == 'info':
            return True  # Silently skip info-level SMS

        try:
            formatted = self.format_message(message, level)
            # Truncate to SMS limit
            if len(formatted) > 1500:
                formatted = formatted[:1497] + "..."

            url = f"https://api.twilio.com/2010-04-01/Accounts/{self.account_sid}/Messages.json"

            response = requests.post(
                url,
                data={
                    'From': self.from_number,
                    'To': self.to_number,
                    'Body': formatted,
                },
                auth=(self.account_sid, self.auth_token),
                timeout=10
            )

            if response.status_code == 201:
                return True
            else:
                logger.error(f"Twilio error: {response.status_code} {response.text}")
                return False

        except Exception as e:
            logger.error(f"SMS notification failed: {e}")
            return False
