"""
Telegram Notification Channel for {strategy_name}
Generated by CBT Framework

Sends notifications via Telegram Bot API.
Setup: Create bot with @BotFather → get token → get chat_id → set in .env
"""

import os
import requests
import logging
from .base import BaseNotifier

logger = logging.getLogger(__name__)


class TelegramNotifier(BaseNotifier):
    """Send notifications via Telegram bot."""

    def __init__(self):
        self.bot_token = os.getenv('TELEGRAM_BOT_TOKEN')
        self.chat_id = os.getenv('TELEGRAM_CHAT_ID')

        if not self.bot_token or not self.chat_id:
            logger.warning("TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set in .env")

    def send(self, message: str, level: str = 'info') -> bool:
        """Send message via Telegram."""
        if not self.bot_token or not self.chat_id:
            return False

        try:
            formatted = self.format_message(message, level)
            url = f"https://api.telegram.org/bot{self.bot_token}/sendMessage"

            payload = {
                'chat_id': self.chat_id,
                'text': formatted,
                'parse_mode': 'HTML',
            }

            response = requests.post(url, json=payload, timeout=10)
            result = response.json()

            if result.get('ok'):
                return True
            else:
                logger.error(f"Telegram error: {result.get('description')}")
                return False

        except Exception as e:
            logger.error(f"Telegram notification failed: {e}")
            return False
