"""
Base Bot for {strategy_name}
Generated by CBT Framework

Abstract base class for exchange-specific trading bots.
Handles common logic: signal execution, safety checks, notifications, logging.
"""

import os
import time
import logging
import signal as sig
from abc import ABC, abstractmethod
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv
import yaml

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.FileHandler('logs/bot.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class BaseBot(ABC):
    """
    Abstract base class for live trading bots.

    Subclass this for each exchange and implement:
    - connect()
    - get_latest_candles()
    - place_order()
    - get_position()
    - close_position()
    - get_balance()
    """

    def __init__(self, config_path: str = "config.yaml", mode: str = "paper"):
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)

        self.mode = mode  # 'paper' or 'live'
        self.running = True
        self.start_time = datetime.now()

        # Safety parameters
        live_config = self.config.get('live', {})
        self.kill_switch_enabled = live_config.get('kill_switch', True)
        self.kill_switch_dd = live_config.get('kill_switch_drawdown', 10.0)
        self.max_position_size = live_config.get('max_position_size')

        # Tracking
        self.initial_balance = 0.0
        self.peak_balance = 0.0
        self.trades_today = 0
        self.total_trades = 0
        self.trade_log = []

        # Graceful shutdown
        sig.signal(sig.SIGINT, self._handle_shutdown)
        sig.signal(sig.SIGTERM, self._handle_shutdown)

        # Create logs directory
        Path('logs').mkdir(exist_ok=True)

    @abstractmethod
    def connect(self) -> bool:
        """Connect to exchange API. Returns True if successful."""
        pass

    @abstractmethod
    def get_latest_candles(self, symbol: str, timeframe: str, limit: int = 100):
        """Fetch latest OHLCV candles from exchange."""
        pass

    @abstractmethod
    def place_order(self, symbol: str, side: str, amount: float,
                    order_type: str = 'market', price: float = None) -> dict:
        """Place an order on the exchange. Returns order info dict."""
        pass

    @abstractmethod
    def get_position(self, symbol: str) -> dict:
        """Get current position for symbol. Returns position info dict."""
        pass

    @abstractmethod
    def close_position(self, symbol: str) -> dict:
        """Close all positions for symbol. Returns close info dict."""
        pass

    @abstractmethod
    def get_balance(self) -> float:
        """Get current account balance."""
        pass

    def run(self, symbol: str, timeframe: str, interval_seconds: int = 60):
        """
        Main bot loop.

        Args:
            symbol: Trading pair (e.g., 'BTC/USDT')
            timeframe: Candle timeframe (e.g., '1h', '5m')
            interval_seconds: Sleep between checks
        """
        logger.info(f"Starting bot: {symbol} {timeframe} [{self.mode} mode]")

        if not self.connect():
            logger.error("Failed to connect to exchange")
            return

        self.initial_balance = self.get_balance()
        self.peak_balance = self.initial_balance
        logger.info(f"Initial balance: {self.initial_balance}")

        self._notify(f"Bot started\nMode: {self.mode}\nSymbol: {symbol}\nBalance: {self.initial_balance}")

        while self.running:
            try:
                # Fetch latest data
                candles = self.get_latest_candles(symbol, timeframe)

                # Generate signal from strategy
                signal = self._generate_signal(candles)

                # Get current position
                position = self.get_position(symbol)

                # Execute trading logic
                self._execute_logic(symbol, signal, position)

                # Safety checks
                self._check_safety()

                # Sleep
                time.sleep(interval_seconds)

            except Exception as e:
                logger.error(f"Bot error: {e}", exc_info=True)
                self._notify(f"ERROR: {e}", level='critical')
                time.sleep(interval_seconds * 2)  # Back off on error

        logger.info("Bot stopped")
        self._notify("Bot stopped")

    def _generate_signal(self, candles) -> dict:
        """Generate trading signal from latest candles. Override for custom logic."""
        # Default: import strategy and use its signal generation
        # This should be customized per strategy
        return {'direction': 0, 'confidence': 0.0}

    def _execute_logic(self, symbol: str, signal: dict, position: dict):
        """Execute trading logic based on signal and current position."""
        direction = signal.get('direction', 0)
        confidence = signal.get('confidence', 0.0)

        has_position = position.get('size', 0) != 0
        position_side = position.get('side', None)

        # Check for exit
        if has_position:
            should_exit = False
            if direction != 0 and (
                (position_side == 'long' and direction == -1) or
                (position_side == 'short' and direction == 1)
            ):
                should_exit = True

            if should_exit:
                result = self.close_position(symbol)
                self._log_trade('exit', symbol, result)
                self._notify(f"Closed {position_side} position on {symbol}")

        # Check for entry
        if not has_position and direction != 0 and confidence > 0:
            side = 'buy' if direction == 1 else 'sell'
            amount = self._calculate_position_size(confidence)

            if amount > 0:
                result = self.place_order(symbol, side, amount)
                self._log_trade('entry', symbol, result)
                self._notify(f"Opened {'long' if direction == 1 else 'short'} on {symbol}\nSize: {amount}")

    def _calculate_position_size(self, confidence: float) -> float:
        """Calculate position size with safety limits."""
        balance = self.get_balance()
        sizing = self.config['sizing']

        if sizing['mode'] == 'percent':
            amount = balance * (sizing['percent_per_trade'] / 100)
        elif sizing['mode'] == 'fixed':
            amount = sizing['fixed_amount']
        else:
            amount = balance * confidence * 0.25  # Quarter Kelly

        # Apply leverage
        if self.config['leverage']['enabled']:
            amount *= self.config['leverage']['default']

        # Apply max position limit
        if self.max_position_size and amount > self.max_position_size:
            amount = self.max_position_size

        return amount

    def _check_safety(self):
        """Run safety checks including kill switch."""
        if not self.kill_switch_enabled:
            return

        balance = self.get_balance()
        self.peak_balance = max(self.peak_balance, balance)

        drawdown = (self.peak_balance - balance) / self.peak_balance * 100

        if drawdown >= self.kill_switch_dd:
            logger.critical(f"KILL SWITCH: Drawdown {drawdown:.1f}% >= {self.kill_switch_dd}%")
            self._notify(
                f"KILL SWITCH TRIGGERED\nDrawdown: {drawdown:.1f}%\nClosing all positions",
                level='critical'
            )
            # Close all positions
            try:
                self.close_position('all')
            except Exception as e:
                logger.error(f"Error closing positions: {e}")
            self.running = False

    def _log_trade(self, action: str, symbol: str, result: dict):
        """Log trade to file and memory."""
        trade = {
            'timestamp': datetime.now().isoformat(),
            'action': action,
            'symbol': symbol,
            'mode': self.mode,
            **result
        }
        self.trade_log.append(trade)
        self.total_trades += 1
        self.trades_today += 1
        logger.info(f"Trade: {action} {symbol} - {result}")

    def _notify(self, message: str, level: str = 'info'):
        """Send notification. Override to add notification channels."""
        logger.info(f"Notification [{level}]: {message}")

    def _handle_shutdown(self, signum, frame):
        """Graceful shutdown handler."""
        logger.info("Shutdown signal received")
        self.running = False
