"""
Binance Exchange Client for {strategy_name}
Generated by CBT Framework

Uses ccxt for Binance API interaction.
Supports: Spot, USDT-M Futures, COIN-M Futures.
"""

import os
import ccxt
import logging

logger = logging.getLogger(__name__)


class BinanceClient:
    """Binance exchange client using ccxt."""

    def __init__(self, mode: str = "paper", market_type: str = "swap"):
        self.mode = mode
        self.market_type = market_type  # 'spot', 'swap' (USDT-M), 'future' (COIN-M)
        self.exchange = None

    def connect(self) -> bool:
        """Connect to Binance API."""
        try:
            config = {
                'apiKey': os.getenv('EXCHANGE_API_KEY'),
                'secret': os.getenv('EXCHANGE_API_SECRET'),
                'sandbox': self.mode == 'paper',
                'options': {
                    'defaultType': self.market_type,
                },
                'enableRateLimit': True,
            }

            self.exchange = ccxt.binance(config)
            self.exchange.load_markets()

            mode_str = 'testnet' if self.mode == 'paper' else 'mainnet'
            logger.info(f"Connected to Binance {self.market_type} ({mode_str})")
            return True

        except Exception as e:
            logger.error(f"Binance connection failed: {e}")
            return False

    def get_latest_candles(self, symbol: str, timeframe: str, limit: int = 100) -> list:
        """Fetch OHLCV candles."""
        try:
            ohlcv = self.exchange.fetch_ohlcv(symbol, timeframe, limit=limit)
            return ohlcv
        except Exception as e:
            logger.error(f"Error fetching candles: {e}")
            return []

    def place_order(self, symbol: str, side: str, amount: float,
                    order_type: str = 'market', price: float = None) -> dict:
        """Place order on Binance."""
        try:
            if self.mode == 'paper' and not self.exchange.urls.get('test'):
                import time
                ticker = self.exchange.fetch_ticker(symbol)
                return {
                    'id': f'paper_{int(time.time())}',
                    'side': side,
                    'amount': amount,
                    'price': ticker['last'],
                    'status': 'filled',
                    'mode': 'paper'
                }

            params = {}
            if self.market_type == 'swap':
                params['positionSide'] = 'BOTH'  # Hedge mode off

            if order_type == 'market':
                order = self.exchange.create_order(symbol, 'market', side, amount, params=params)
            else:
                order = self.exchange.create_order(symbol, 'limit', side, amount, price, params=params)

            return {
                'id': order['id'],
                'side': order['side'],
                'amount': order['amount'],
                'price': order.get('average', order.get('price')),
                'status': order['status'],
                'fee': order.get('fee', {}).get('cost', 0),
            }

        except Exception as e:
            logger.error(f"Order error: {e}")
            return {'error': str(e)}

    def get_position(self, symbol: str) -> dict:
        """Get current position."""
        try:
            if self.market_type in ('swap', 'future'):
                positions = self.exchange.fetch_positions([symbol])
                for pos in positions:
                    if abs(pos['contracts']) > 0:
                        return {
                            'symbol': symbol,
                            'side': pos['side'],
                            'size': abs(pos['contracts']),
                            'entry_price': pos['entryPrice'],
                            'unrealized_pnl': pos['unrealizedPnl'],
                            'leverage': pos['leverage'],
                        }
            else:
                # Spot: check balance
                balance = self.exchange.fetch_balance()
                base = symbol.split('/')[0]
                amount = float(balance.get(base, {}).get('total', 0))
                if amount > 0:
                    return {
                        'symbol': symbol,
                        'side': 'long',
                        'size': amount,
                        'entry_price': None,
                        'unrealized_pnl': None,
                    }

            return {'symbol': symbol, 'side': None, 'size': 0}

        except Exception as e:
            logger.error(f"Position error: {e}")
            return {'symbol': symbol, 'side': None, 'size': 0}

    def close_position(self, symbol: str) -> dict:
        """Close position."""
        try:
            position = self.get_position(symbol)
            if position['size'] == 0:
                return {'status': 'no_position'}

            side = 'sell' if position['side'] == 'long' else 'buy'
            return self.place_order(symbol, side, position['size'])

        except Exception as e:
            logger.error(f"Close error: {e}")
            return {'error': str(e)}

    def get_balance(self) -> float:
        """Get USDT balance."""
        try:
            balance = self.exchange.fetch_balance()
            return float(balance.get('USDT', {}).get('total', 0))
        except Exception as e:
            logger.error(f"Balance error: {e}")
            return 0.0
