"""
Hyperliquid Exchange Client for {strategy_name}
Generated by CBT Framework

Uses ccxt for Hyperliquid API interaction.
Supports: Perpetual futures (on-chain DEX).
"""

import os
import ccxt
import logging

logger = logging.getLogger(__name__)


class HyperliquidClient:
    """Hyperliquid exchange client using ccxt."""

    def __init__(self, mode: str = "paper"):
        self.mode = mode
        self.exchange = None

    def connect(self) -> bool:
        """Connect to Hyperliquid API."""
        try:
            config = {
                'apiKey': os.getenv('EXCHANGE_API_KEY'),
                'secret': os.getenv('EXCHANGE_API_SECRET'),
                'sandbox': self.mode == 'paper',
                'enableRateLimit': True,
                'options': {
                    'defaultType': 'swap',
                },
            }

            # Hyperliquid uses wallet address as API key
            wallet = os.getenv('HYPERLIQUID_WALLET')
            if wallet:
                config['walletAddress'] = wallet

            self.exchange = ccxt.hyperliquid(config)
            self.exchange.load_markets()

            mode_str = 'testnet' if self.mode == 'paper' else 'mainnet'
            logger.info(f"Connected to Hyperliquid ({mode_str})")
            return True

        except Exception as e:
            logger.error(f"Hyperliquid connection failed: {e}")
            return False

    def get_latest_candles(self, symbol: str, timeframe: str, limit: int = 100) -> list:
        """Fetch OHLCV candles."""
        try:
            ohlcv = self.exchange.fetch_ohlcv(symbol, timeframe, limit=limit)
            return ohlcv
        except Exception as e:
            logger.error(f"Error fetching candles: {e}")
            return []

    def place_order(self, symbol: str, side: str, amount: float,
                    order_type: str = 'market', price: float = None) -> dict:
        """Place order on Hyperliquid."""
        try:
            if self.mode == 'paper' and not self.exchange.urls.get('test'):
                import time
                ticker = self.exchange.fetch_ticker(symbol)
                return {
                    'id': f'paper_{int(time.time())}',
                    'side': side,
                    'amount': amount,
                    'price': ticker['last'],
                    'status': 'filled',
                    'mode': 'paper'
                }

            if order_type == 'market':
                order = self.exchange.create_order(symbol, 'market', side, amount)
            else:
                order = self.exchange.create_order(symbol, 'limit', side, amount, price)

            return {
                'id': order['id'],
                'side': order['side'],
                'amount': order['amount'],
                'price': order.get('average', order.get('price')),
                'status': order['status'],
                'fee': order.get('fee', {}).get('cost', 0),
            }

        except Exception as e:
            logger.error(f"Order error: {e}")
            return {'error': str(e)}

    def get_position(self, symbol: str) -> dict:
        """Get current position."""
        try:
            positions = self.exchange.fetch_positions([symbol])
            for pos in positions:
                if abs(pos['contracts']) > 0:
                    return {
                        'symbol': symbol,
                        'side': pos['side'],
                        'size': abs(pos['contracts']),
                        'entry_price': pos['entryPrice'],
                        'unrealized_pnl': pos['unrealizedPnl'],
                        'leverage': pos['leverage'],
                    }
            return {'symbol': symbol, 'side': None, 'size': 0}

        except Exception as e:
            logger.error(f"Position error: {e}")
            return {'symbol': symbol, 'side': None, 'size': 0}

    def close_position(self, symbol: str) -> dict:
        """Close position."""
        try:
            position = self.get_position(symbol)
            if position['size'] == 0:
                return {'status': 'no_position'}

            side = 'sell' if position['side'] == 'long' else 'buy'
            return self.place_order(symbol, side, position['size'])

        except Exception as e:
            logger.error(f"Close error: {e}")
            return {'error': str(e)}

    def get_balance(self) -> float:
        """Get USDC balance."""
        try:
            balance = self.exchange.fetch_balance()
            return float(balance.get('USDC', {}).get('total', 0))
        except Exception as e:
            logger.error(f"Balance error: {e}")
            return 0.0
