"""
Kraken Exchange Client for {strategy_name}
Generated by CBT Framework

Uses ccxt for Kraken API interaction.
Supports: Spot, Futures (Kraken Futures).
"""

import os
import ccxt
import logging

logger = logging.getLogger(__name__)


class KrakenClient:
    """Kraken exchange client using ccxt."""

    def __init__(self, mode: str = "paper"):
        self.mode = mode
        self.exchange = None

    def connect(self) -> bool:
        """Connect to Kraken API."""
        try:
            config = {
                'apiKey': os.getenv('EXCHANGE_API_KEY'),
                'secret': os.getenv('EXCHANGE_API_SECRET'),
                'enableRateLimit': True,
            }

            self.exchange = ccxt.kraken(config)
            self.exchange.load_markets()

            logger.info(f"Connected to Kraken ({'paper' if self.mode == 'paper' else 'live'})")
            return True

        except Exception as e:
            logger.error(f"Kraken connection failed: {e}")
            return False

    def get_latest_candles(self, symbol: str, timeframe: str, limit: int = 100) -> list:
        """Fetch OHLCV candles."""
        try:
            ohlcv = self.exchange.fetch_ohlcv(symbol, timeframe, limit=limit)
            return ohlcv
        except Exception as e:
            logger.error(f"Error fetching candles: {e}")
            return []

    def place_order(self, symbol: str, side: str, amount: float,
                    order_type: str = 'market', price: float = None) -> dict:
        """Place order on Kraken."""
        try:
            if self.mode == 'paper':
                import time
                ticker = self.exchange.fetch_ticker(symbol)
                return {
                    'id': f'paper_{int(time.time())}',
                    'side': side,
                    'amount': amount,
                    'price': ticker['last'],
                    'status': 'filled',
                    'mode': 'paper'
                }

            if order_type == 'market':
                order = self.exchange.create_order(symbol, 'market', side, amount)
            else:
                order = self.exchange.create_order(symbol, 'limit', side, amount, price)

            return {
                'id': order['id'],
                'side': order['side'],
                'amount': order['amount'],
                'price': order.get('average', order.get('price')),
                'status': order['status'],
                'fee': order.get('fee', {}).get('cost', 0),
            }

        except Exception as e:
            logger.error(f"Order error: {e}")
            return {'error': str(e)}

    def get_position(self, symbol: str) -> dict:
        """Get current position (spot: check balance)."""
        try:
            balance = self.exchange.fetch_balance()
            base = symbol.split('/')[0]
            amount = float(balance.get(base, {}).get('total', 0))
            if amount > 0:
                return {
                    'symbol': symbol,
                    'side': 'long',
                    'size': amount,
                    'entry_price': None,
                    'unrealized_pnl': None,
                }
            return {'symbol': symbol, 'side': None, 'size': 0}

        except Exception as e:
            logger.error(f"Position error: {e}")
            return {'symbol': symbol, 'side': None, 'size': 0}

    def close_position(self, symbol: str) -> dict:
        """Close position (sell all of base asset)."""
        try:
            position = self.get_position(symbol)
            if position['size'] == 0:
                return {'status': 'no_position'}

            return self.place_order(symbol, 'sell', position['size'])

        except Exception as e:
            logger.error(f"Close error: {e}")
            return {'error': str(e)}

    def get_balance(self) -> float:
        """Get USD/USDT balance."""
        try:
            balance = self.exchange.fetch_balance()
            usd = float(balance.get('USD', {}).get('total', 0))
            usdt = float(balance.get('USDT', {}).get('total', 0))
            return usd + usdt
        except Exception as e:
            logger.error(f"Balance error: {e}")
            return 0.0
