"""
Fast Data Loader for {strategy_name}
Generated by CBT Framework (Fast Engine: Polars)

Uses Polars for high-performance data loading with lazy evaluation.
Outputs NumPy arrays for downstream Numba-compiled processing.
"""

import polars as pl
import numpy as np
from pathlib import Path
from typing import Dict, Optional, Tuple


class FastDataLoader:
    """Load and validate strategy data using Polars lazy frames."""

    def __init__(self, data_dir: str = "Data"):
        self.data_dir = Path(data_dir)
        self.lazy_frames: Dict[str, pl.LazyFrame] = {}
        self._collected: Optional[pl.DataFrame] = None

    def load_all(self) -> Dict[str, pl.LazyFrame]:
        """
        Load all required datasets as lazy frames.
        Lazy evaluation defers computation until .collect() is called.
        """
        for file in self.data_dir.iterdir():
            if file.suffix == '.parquet':
                self.lazy_frames[file.stem] = pl.scan_parquet(file)
            elif file.suffix == '.csv':
                self.lazy_frames[file.stem] = pl.scan_csv(file, try_parse_dates=True)

        if not self.lazy_frames:
            raise FileNotFoundError(f"No data files found in {self.data_dir}")

        return self.lazy_frames

    def validate(self) -> bool:
        """Validate data integrity on a sample."""
        for name, lf in self.lazy_frames.items():
            df = lf.head(1000).collect()

            # Check for required OHLCV columns
            required = {'open', 'high', 'low', 'close'}
            cols_lower = {c.lower() for c in df.columns}
            missing = required - cols_lower
            if missing:
                print(f"WARNING [{name}]: Missing columns: {missing}")
                return False

            # Check for nulls
            null_counts = df.null_count()
            total_nulls = sum(null_counts.row(0))
            if total_nulls > 0:
                print(f"WARNING [{name}]: {total_nulls} null values detected")

            # Check for duplicate timestamps
            if 'timestamp' in cols_lower or 'date' in cols_lower or 'datetime' in cols_lower:
                time_col = next(c for c in df.columns if c.lower() in ('timestamp', 'date', 'datetime'))
                dupes = df.select(pl.col(time_col).is_duplicated().sum()).item()
                if dupes > 0:
                    print(f"WARNING [{name}]: {dupes} duplicate timestamps")

        return True

    def get_aligned(
        self,
        start: Optional[str] = None,
        end: Optional[str] = None
    ) -> pl.DataFrame:
        """
        Collect and merge all lazy frames into a single aligned DataFrame.
        Applies date filters before collection for memory efficiency.
        """
        if len(self.lazy_frames) == 1:
            lf = list(self.lazy_frames.values())[0]
        else:
            # Join on timestamp/date column
            frames = list(self.lazy_frames.values())
            lf = frames[0]
            for other in frames[1:]:
                # Find common time column
                lf = lf.join(other, on=self._find_time_col(lf), how="inner")

        # Apply date filters
        time_col = self._find_time_col(lf)
        if start:
            lf = lf.filter(pl.col(time_col) >= start)
        if end:
            lf = lf.filter(pl.col(time_col) <= end)

        # Sort by time
        lf = lf.sort(time_col)

        self._collected = lf.collect()
        return self._collected

    def to_numpy_arrays(self) -> Dict[str, np.ndarray]:
        """
        Convert collected DataFrame to NumPy arrays for Numba processing.
        Returns dict with column names as keys, contiguous float64 arrays as values.
        """
        if self._collected is None:
            raise RuntimeError("Call get_aligned() before to_numpy_arrays()")

        arrays = {}
        for col in self._collected.columns:
            series = self._collected[col]
            if series.dtype in (pl.Float64, pl.Float32, pl.Int64, pl.Int32, pl.Int16, pl.Int8):
                arrays[col] = series.to_numpy().astype(np.float64)
            elif series.dtype == pl.Boolean:
                arrays[col] = series.to_numpy().astype(np.float64)
            # Skip non-numeric columns (timestamps, strings)

        return arrays

    def _find_time_col(self, lf: pl.LazyFrame) -> str:
        """Find the timestamp/date column name."""
        schema = lf.collect_schema()
        for col_name, dtype in schema.items():
            if col_name.lower() in ('timestamp', 'date', 'datetime', 'time'):
                return col_name
            if dtype in (pl.Datetime, pl.Date):
                return col_name
        raise ValueError("No timestamp column found. Expected: timestamp, date, or datetime")

    def summary(self) -> str:
        """Print data summary."""
        if self._collected is None:
            return "No data collected yet. Call get_aligned() first."

        lines = [
            f"Shape: {self._collected.shape}",
            f"Columns: {self._collected.columns}",
            f"Memory: {self._collected.estimated_size('mb'):.1f} MB",
            f"Dtypes:\n{self._collected.dtypes}",
        ]
        return "\n".join(lines)
