"""
Fast Feature Engineering for {strategy_name}
Generated by CBT Framework (Fast Engine: NumPy)

All features computed on NumPy arrays for maximum performance.
IMPORTANT: All features use array shifting to prevent lookahead bias.
At time index t, only data from indices < t is used.
"""

import numpy as np
from typing import Dict


def rolling_mean(arr: np.ndarray, window: int) -> np.ndarray:
    """Compute rolling mean using cumsum trick. O(n) complexity."""
    cumsum = np.cumsum(arr)
    cumsum = np.insert(cumsum, 0, 0)
    result = (cumsum[window:] - cumsum[:-window]) / window
    # Pad front with NaN to maintain array length
    return np.concatenate([np.full(window - 1, np.nan), result])


def rolling_std(arr: np.ndarray, window: int) -> np.ndarray:
    """Compute rolling standard deviation."""
    mean = rolling_mean(arr, window)
    mean_sq = rolling_mean(arr ** 2, window)
    variance = mean_sq - mean ** 2
    # Clamp negative variance (floating point artifacts)
    variance = np.maximum(variance, 0)
    return np.sqrt(variance)


def shift(arr: np.ndarray, periods: int = 1) -> np.ndarray:
    """Shift array by N periods (positive = shift right/lag)."""
    result = np.empty_like(arr)
    if periods > 0:
        result[:periods] = np.nan
        result[periods:] = arr[:-periods]
    elif periods < 0:
        result[periods:] = np.nan
        result[:periods] = arr[-periods:]
    else:
        result[:] = arr
    return result


def ema(arr: np.ndarray, span: int) -> np.ndarray:
    """Compute exponential moving average."""
    alpha = 2.0 / (span + 1)
    result = np.empty_like(arr)
    result[0] = arr[0]
    for i in range(1, len(arr)):
        result[i] = alpha * arr[i] + (1 - alpha) * result[i - 1]
    return result


class FastFeatureGenerator:
    """Generate features using NumPy arrays with strict lookahead prevention."""

    def __init__(self, params: dict):
        self.params = params

    def generate(self, arrays: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        """
        Generate all features from NumPy arrays.

        CRITICAL: Every feature must be shifted by 1 to prevent lookahead.
        At bar t, we can only use data available at the OPEN of bar t,
        which means data from bars 0..t-1.

        Args:
            arrays: Dict of column_name -> numpy array (from FastDataLoader.to_numpy_arrays())

        Returns:
            Dict of feature_name -> numpy array (all same length as input)
        """
        close = arrays['close']
        high = arrays['high']
        low = arrays['low']
        open_ = arrays['open']
        volume = arrays.get('volume', np.zeros_like(close))

        n = len(close)
        features = {}

        # --- Returns (shifted to prevent lookahead) ---
        raw_returns_1 = np.empty(n)
        raw_returns_1[0] = 0
        raw_returns_1[1:] = (close[1:] - close[:-1]) / close[:-1]
        features['return_1'] = shift(raw_returns_1, 1)

        raw_returns_5 = np.empty(n)
        raw_returns_5[:5] = 0
        raw_returns_5[5:] = (close[5:] - close[:-5]) / close[:-5]
        features['return_5'] = shift(raw_returns_5, 1)

        # --- Moving Averages (shifted) ---
        for window in [10, 20, 50, 200]:
            ma = rolling_mean(close, window)
            features[f'sma_{window}'] = shift(ma, 1)

        # --- Volatility (shifted) ---
        for window in [10, 20]:
            std = rolling_std(raw_returns_1, window)
            features[f'volatility_{window}'] = shift(std, 1)

        # --- ATR (shifted) ---
        tr = np.maximum(
            high - low,
            np.maximum(
                np.abs(high - shift(close, 1)),
                np.abs(low - shift(close, 1))
            )
        )
        features['atr_14'] = shift(rolling_mean(tr, 14), 1)

        # --- RSI (shifted) ---
        features['rsi_14'] = shift(self._compute_rsi(close, 14), 1)

        # --- MACD (shifted) ---
        ema12 = ema(close, 12)
        ema26 = ema(close, 26)
        macd_line = ema12 - ema26
        macd_signal = ema(macd_line, 9)
        features['macd'] = shift(macd_line, 1)
        features['macd_signal'] = shift(macd_signal, 1)
        features['macd_histogram'] = shift(macd_line - macd_signal, 1)

        # --- Bollinger Bands (shifted) ---
        bb_ma = rolling_mean(close, 20)
        bb_std = rolling_std(close, 20)
        features['bb_upper'] = shift(bb_ma + 2 * bb_std, 1)
        features['bb_lower'] = shift(bb_ma - 2 * bb_std, 1)
        features['bb_width'] = shift((bb_ma + 2 * bb_std - (bb_ma - 2 * bb_std)) / bb_ma, 1)

        # --- Volume features (shifted) ---
        features['volume_sma_20'] = shift(rolling_mean(volume, 20), 1)
        vol_ma = rolling_mean(volume, 20)
        vol_ma_safe = np.where(vol_ma == 0, 1, vol_ma)
        features['volume_ratio'] = shift(volume / vol_ma_safe, 1)

        # --- Price features (shifted) ---
        features['close_to_sma20'] = shift(close / np.where(rolling_mean(close, 20) == 0, 1, rolling_mean(close, 20)), 1)

        return features

    def _compute_rsi(self, close: np.ndarray, period: int) -> np.ndarray:
        """Compute RSI from close prices."""
        delta = np.diff(close, prepend=close[0])
        gains = np.where(delta > 0, delta, 0)
        losses = np.where(delta < 0, -delta, 0)

        avg_gain = np.empty_like(close)
        avg_loss = np.empty_like(close)
        avg_gain[:period] = np.nan
        avg_loss[:period] = np.nan

        avg_gain[period] = np.mean(gains[1:period + 1])
        avg_loss[period] = np.mean(losses[1:period + 1])

        for i in range(period + 1, len(close)):
            avg_gain[i] = (avg_gain[i - 1] * (period - 1) + gains[i]) / period
            avg_loss[i] = (avg_loss[i - 1] * (period - 1) + losses[i]) / period

        avg_loss_safe = np.where(avg_loss == 0, 1e-10, avg_loss)
        rs = avg_gain / avg_loss_safe
        rsi = 100 - (100 / (1 + rs))
        return rsi

    def validate_no_lookahead(self, features: Dict[str, np.ndarray]) -> bool:
        """Verify no future data leakage by checking first values are NaN."""
        for name, arr in features.items():
            if not np.isnan(arr[0]):
                print(f"LOOKAHEAD WARNING: Feature '{name}' has value at index 0. "
                      f"Should be NaN if properly shifted.")
                return False
        return True
