"""
Fast Signal Generation for {strategy_name}
Generated by CBT Framework (Fast Engine: NumPy)

Generates trading signals as NumPy arrays for Numba-compiled backtest.
Output: direction array (1=long, -1=short, 0=flat) and confidence array (0-1).
"""

import numpy as np
from typing import Dict, Tuple


class FastSignalGenerator:
    """Generate trading signals from NumPy feature arrays."""

    def __init__(self, params: dict):
        self.params = params
        self.min_confidence = params.get('min_confidence', 0.3)

    def generate_all(
        self,
        features: Dict[str, np.ndarray]
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Generate signals for entire dataset.

        Args:
            features: Dict of feature_name -> numpy array

        Returns:
            Tuple of (directions, confidences):
                - directions: int array, 1=long, -1=short, 0=flat
                - confidences: float array, 0.0 to 1.0
        """
        n = len(next(iter(features.values())))
        directions = np.zeros(n, dtype=np.int64)
        confidences = np.zeros(n, dtype=np.float64)

        # Compute component signals
        trend_dir, trend_conf = self._trend_signal(features)
        momentum_dir, momentum_conf = self._momentum_signal(features)
        volume_dir, volume_conf = self._volume_signal(features)

        # Weighted combination
        weights = self.params.get('signal_weights', {
            'trend': 0.4,
            'momentum': 0.4,
            'volume': 0.2
        })

        combined_score = (
            trend_dir * trend_conf * weights.get('trend', 0.4) +
            momentum_dir * momentum_conf * weights.get('momentum', 0.4) +
            volume_dir * volume_conf * weights.get('volume', 0.2)
        )

        # Determine direction and confidence
        directions = np.sign(combined_score).astype(np.int64)
        confidences = np.abs(combined_score)

        # Apply minimum confidence filter
        below_threshold = confidences < self.min_confidence
        directions[below_threshold] = 0
        confidences[below_threshold] = 0.0

        return directions, confidences

    def _trend_signal(
        self, features: Dict[str, np.ndarray]
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Trend-following signal from moving average crossovers."""
        n = len(next(iter(features.values())))
        directions = np.zeros(n)
        confidences = np.zeros(n)

        sma_fast = features.get('sma_10', np.zeros(n))
        sma_slow = features.get('sma_50', np.zeros(n))

        # MA crossover direction
        with np.errstate(invalid='ignore'):
            valid = ~(np.isnan(sma_fast) | np.isnan(sma_slow))
            safe_slow = np.where(sma_slow == 0, 1, sma_slow)
            spread = np.where(valid, (sma_fast - sma_slow) / safe_slow, 0)

        directions = np.sign(spread)
        confidences = np.minimum(np.abs(spread) * 10, 1.0)  # Scale to 0-1

        return directions, confidences

    def _momentum_signal(
        self, features: Dict[str, np.ndarray]
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Momentum signal from RSI."""
        n = len(next(iter(features.values())))
        directions = np.zeros(n)
        confidences = np.zeros(n)

        rsi = features.get('rsi_14', np.full(n, 50.0))

        with np.errstate(invalid='ignore'):
            valid = ~np.isnan(rsi)
            # Oversold = long signal, overbought = short signal
            oversold = valid & (rsi < 30)
            overbought = valid & (rsi > 70)
            directions[oversold] = 1
            directions[overbought] = -1
            # Confidence scales with distance from 50
            confidences = np.where(valid, np.abs(rsi - 50) / 50, 0)

        return directions, confidences

    def _volume_signal(
        self, features: Dict[str, np.ndarray]
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Volume confirmation signal."""
        n = len(next(iter(features.values())))
        directions = np.ones(n)  # Volume is directionally neutral
        confidences = np.zeros(n)

        vol_ratio = features.get('volume_ratio', np.ones(n))

        with np.errstate(invalid='ignore'):
            valid = ~np.isnan(vol_ratio)
            # Higher volume = higher confidence
            confidences = np.where(valid, np.minimum(vol_ratio / 2, 1.0), 0)

        return directions, confidences
