"""
Fast Strategy for {strategy_name}
Generated by CBT Framework (Fast Engine: NumPy + Numba)

Strategy orchestrator that connects data loading, feature generation,
signal generation, and backtesting using fast array-based operations.
"""

import numpy as np
from typing import Dict, Optional, Tuple
from pathlib import Path
import yaml

from src.data_loader import FastDataLoader
from src.features import FastFeatureGenerator
from src.signals import FastSignalGenerator


class FastStrategy:
    """
    {Strategy description}

    Entry: {entry conditions summary}
    Exit: {exit conditions summary}

    Uses Polars for data, NumPy for features/signals, Numba for backtest.
    """

    def __init__(self, config_path: str = "config.yaml"):
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)

        self.params = self.config.get('strategy_params', {})

        # Initialize components
        self.data_loader = FastDataLoader()
        self.feature_gen = FastFeatureGenerator(self.params)
        self.signal_gen = FastSignalGenerator(self.params)

        # Data arrays (populated by initialize())
        self.arrays: Dict[str, np.ndarray] = {}
        self.features: Dict[str, np.ndarray] = {}
        self.directions: Optional[np.ndarray] = None
        self.confidences: Optional[np.ndarray] = None

    def initialize(self) -> None:
        """Load data, generate features and signals. Prepare for backtesting."""
        # Load data with Polars
        self.data_loader.load_all()
        self.data_loader.validate()

        df = self.data_loader.get_aligned(
            start=self.config['time'].get('start_date'),
            end=self.config['time'].get('end_date')
        )

        # Convert to NumPy arrays
        self.arrays = self.data_loader.to_numpy_arrays()

        # Generate features (all NumPy)
        self.features = self.feature_gen.generate(self.arrays)
        self.feature_gen.validate_no_lookahead(self.features)

        # Generate signals (all NumPy)
        self.directions, self.confidences = self.signal_gen.generate_all(self.features)

        print(f"Strategy initialized:")
        print(f"  Data points: {len(self.arrays['close'])}")
        print(f"  Features: {len(self.features)}")
        print(f"  Signals (non-zero): {np.count_nonzero(self.directions)}")

    def get_backtest_arrays(self) -> Dict[str, np.ndarray]:
        """
        Package all arrays needed for the Numba backtest loop.
        Returns contiguous float64 arrays for optimal JIT performance.
        """
        return {
            'open': np.ascontiguousarray(self.arrays['open'], dtype=np.float64),
            'high': np.ascontiguousarray(self.arrays['high'], dtype=np.float64),
            'low': np.ascontiguousarray(self.arrays['low'], dtype=np.float64),
            'close': np.ascontiguousarray(self.arrays['close'], dtype=np.float64),
            'volume': np.ascontiguousarray(self.arrays.get('volume', np.zeros_like(self.arrays['close'])), dtype=np.float64),
            'directions': np.ascontiguousarray(self.directions, dtype=np.float64),
            'confidences': np.ascontiguousarray(self.confidences, dtype=np.float64),
        }

    def calculate_stop_loss(self, entry_price: float, direction: int) -> float:
        """Calculate stop loss price."""
        sl_config = self.config['risk']['stop_loss']
        if not sl_config['enabled']:
            return 0.0  # 0 means no stop loss

        if sl_config['mode'] == 'percent':
            pct = sl_config['percent'] / 100
            if direction == 1:  # long
                return entry_price * (1 - pct)
            else:  # short
                return entry_price * (1 + pct)

        return 0.0

    def calculate_take_profit(self, entry_price: float, direction: int) -> float:
        """Calculate take profit price."""
        tp_config = self.config['risk']['take_profit']
        if not tp_config['enabled']:
            return 0.0  # 0 means no take profit

        if tp_config['mode'] == 'percent':
            pct = tp_config['percent'] / 100
            if direction == 1:  # long
                return entry_price * (1 + pct)
            else:  # short
                return entry_price * (1 - pct)

        return 0.0
