"""
Data Loader for {strategy_name}
Generated by CBT Framework

Handles loading, validation, and alignment of strategy datasets.
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Dict, List, Optional, Union
from datetime import datetime
import warnings


class DataLoader:
    """
    Load and validate strategy data files.

    Expected data location: Data/ directory
    Supported formats: CSV, Parquet

    Usage:
        loader = DataLoader("Data")
        data = loader.load_all()
        aligned = loader.get_aligned(start="2024-01-01", end="2024-12-31")
    """

    def __init__(self, data_dir: str = "Data"):
        """
        Initialize DataLoader.

        Args:
            data_dir: Directory containing data files
        """
        self.data_dir = Path(data_dir)
        self.data: Dict[str, pd.DataFrame] = {}
        self._validation_errors: List[str] = []

    def load_file(self, filename: str,
                  date_column: str = 'timestamp',
                  parse_dates: bool = True) -> pd.DataFrame:
        """
        Load a single data file.

        Args:
            filename: Name of file in data directory
            date_column: Column to use as index
            parse_dates: Whether to parse dates

        Returns:
            DataFrame with datetime index
        """
        filepath = self.data_dir / filename

        if not filepath.exists():
            raise FileNotFoundError(f"Data file not found: {filepath}")

        # Determine file type and load
        if filepath.suffix == '.parquet':
            df = pd.read_parquet(filepath)
        elif filepath.suffix == '.csv':
            df = pd.read_csv(filepath)
        else:
            raise ValueError(f"Unsupported file format: {filepath.suffix}")

        # Set datetime index
        if date_column in df.columns:
            if parse_dates:
                # Try multiple date formats
                try:
                    df[date_column] = pd.to_datetime(df[date_column])
                except Exception:
                    # Try unix timestamp (milliseconds)
                    df[date_column] = pd.to_datetime(df[date_column], unit='ms')

            df.set_index(date_column, inplace=True)
            df.sort_index(inplace=True)

        return df

    def load_all(self) -> Dict[str, pd.DataFrame]:
        """
        Load all data files from data directory.

        Returns:
            Dictionary mapping filename (without extension) to DataFrame
        """
        if not self.data_dir.exists():
            raise FileNotFoundError(f"Data directory not found: {self.data_dir}")

        # Find all data files
        files = list(self.data_dir.glob("*.csv")) + list(self.data_dir.glob("*.parquet"))

        if not files:
            raise FileNotFoundError(f"No data files found in {self.data_dir}")

        for filepath in files:
            name = filepath.stem  # filename without extension
            try:
                self.data[name] = self.load_file(filepath.name)
                print(f"Loaded: {filepath.name} ({len(self.data[name])} rows)")
            except Exception as e:
                warnings.warn(f"Failed to load {filepath.name}: {e}")

        return self.data

    def validate(self) -> bool:
        """
        Validate loaded data for common issues.

        Checks:
        - No duplicate timestamps
        - No large gaps in data
        - No missing values in critical columns
        - Consistent date ranges across files

        Returns:
            True if validation passes, False otherwise
        """
        self._validation_errors = []

        for name, df in self.data.items():
            # Check for duplicate timestamps
            if df.index.duplicated().any():
                dup_count = df.index.duplicated().sum()
                self._validation_errors.append(
                    f"{name}: {dup_count} duplicate timestamps"
                )

            # Check for missing values
            missing = df.isnull().sum()
            cols_with_missing = missing[missing > 0]
            if len(cols_with_missing) > 0:
                for col, count in cols_with_missing.items():
                    pct = count / len(df) * 100
                    if pct > 5:  # Only warn if > 5% missing
                        self._validation_errors.append(
                            f"{name}.{col}: {pct:.1f}% missing values"
                        )

            # Check for gaps (assuming regular intervals)
            if len(df) > 1:
                diffs = df.index.to_series().diff().dropna()
                median_diff = diffs.median()
                large_gaps = diffs[diffs > median_diff * 2]
                if len(large_gaps) > 0:
                    self._validation_errors.append(
                        f"{name}: {len(large_gaps)} potential gaps in data"
                    )

        if self._validation_errors:
            print("Validation warnings:")
            for error in self._validation_errors:
                print(f"  - {error}")
            return False

        print("Data validation passed!")
        return True

    def get_aligned(self,
                    start: Optional[Union[str, datetime]] = None,
                    end: Optional[Union[str, datetime]] = None,
                    method: str = 'inner') -> pd.DataFrame:
        """
        Get time-aligned merged dataset.

        Args:
            start: Start date/datetime (inclusive)
            end: End date/datetime (inclusive)
            method: Join method ('inner', 'outer', 'left', 'right')

        Returns:
            Merged DataFrame with aligned timestamps
        """
        if not self.data:
            raise RuntimeError("No data loaded. Call load_all() first.")

        # Start with first dataset
        dfs = list(self.data.values())
        names = list(self.data.keys())

        # Add prefix to avoid column conflicts
        result = dfs[0].add_prefix(f"{names[0]}_")

        # Merge remaining datasets
        for name, df in zip(names[1:], dfs[1:]):
            df_prefixed = df.add_prefix(f"{name}_")
            result = result.join(df_prefixed, how=method)

        # If only one dataset, remove prefix
        if len(self.data) == 1:
            result.columns = [col.replace(f"{names[0]}_", "") for col in result.columns]

        # Apply date filters
        if start:
            result = result[result.index >= pd.to_datetime(start)]
        if end:
            result = result[result.index <= pd.to_datetime(end)]

        # Drop rows with any NaN (from join mismatches)
        if method == 'outer':
            initial_len = len(result)
            result = result.dropna()
            dropped = initial_len - len(result)
            if dropped > 0:
                print(f"Dropped {dropped} rows with missing values after alignment")

        return result

    def get_date_range(self) -> tuple:
        """
        Get the common date range across all datasets.

        Returns:
            Tuple of (earliest_start, latest_end)
        """
        if not self.data:
            raise RuntimeError("No data loaded")

        starts = [df.index.min() for df in self.data.values()]
        ends = [df.index.max() for df in self.data.values()]

        return max(starts), min(ends)

    def summary(self) -> str:
        """Generate summary of loaded data."""
        if not self.data:
            return "No data loaded"

        lines = ["Data Summary", "=" * 40]

        for name, df in self.data.items():
            lines.append(f"\n{name}:")
            lines.append(f"  Rows: {len(df):,}")
            lines.append(f"  Columns: {list(df.columns)}")
            lines.append(f"  Date range: {df.index.min()} to {df.index.max()}")

            # Infer frequency
            if len(df) > 1:
                freq = pd.infer_freq(df.index[:100])
                if freq:
                    lines.append(f"  Frequency: {freq}")

        return "\n".join(lines)


# For direct testing
if __name__ == "__main__":
    loader = DataLoader("Data")

    try:
        data = loader.load_all()
        print("\n" + loader.summary())
        loader.validate()

        aligned = loader.get_aligned()
        print(f"\nAligned data shape: {aligned.shape}")
        print(f"Date range: {aligned.index.min()} to {aligned.index.max()}")

    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Please place your data files in the Data/ directory")
