"""
Feature Engineering for {strategy_name}
Generated by CBT Framework

CRITICAL: All features must prevent lookahead bias.
Use .shift(1) for any calculation that includes current bar data.
"""

import pandas as pd
import numpy as np
from typing import List, Optional, Dict, Any
import warnings


class FeatureGenerator:
    """
    Generate trading features with strict lookahead prevention.

    All features are calculated using only data available at time t,
    meaning we use .shift(1) to ensure we don't peek into the future.

    Usage:
        generator = FeatureGenerator(params)
        features = generator.generate(data)
    """

    def __init__(self, params: dict):
        """
        Initialize feature generator.

        Args:
            params: Strategy parameters dictionary
        """
        self.params = params

    def generate(self, data: pd.DataFrame) -> pd.DataFrame:
        """
        Generate all features from raw data.

        IMPORTANT: Every feature calculation must only use past data.
        The value at index t should only depend on data from indices < t.

        Args:
            data: Raw OHLCV data

        Returns:
            DataFrame with original data plus generated features
        """
        df = data.copy()

        # Ensure we have required columns
        required = ['open', 'high', 'low', 'close', 'volume']
        missing = [col for col in required if col not in df.columns]

        # Try to find columns with different names
        column_mapping = self._find_columns(df.columns)
        for std_name, actual_name in column_mapping.items():
            if actual_name and std_name not in df.columns:
                df[std_name] = df[actual_name]

        # Generate features (all shifted to prevent lookahead)
        df = self._add_returns(df)
        df = self._add_volatility(df)
        df = self._add_momentum(df)
        df = self._add_volume_features(df)
        df = self._add_price_features(df)

        # Strategy-specific features
        df = self._add_custom_features(df)

        # Validate no lookahead
        self._validate_no_lookahead(df)

        # Drop initial NaN rows from feature calculation
        df = df.dropna()

        return df

    def _find_columns(self, columns: pd.Index) -> Dict[str, Optional[str]]:
        """Find standard column names in various formats."""
        mapping = {
            'open': None,
            'high': None,
            'low': None,
            'close': None,
            'volume': None
        }

        col_lower = {c.lower(): c for c in columns}

        for std_name in mapping.keys():
            # Try exact match
            if std_name in col_lower:
                mapping[std_name] = col_lower[std_name]
            # Try with prefix (e.g., 'btc_close')
            else:
                for col in col_lower:
                    if col.endswith(f'_{std_name}') or col.endswith(std_name):
                        mapping[std_name] = col_lower[col]
                        break

        return mapping

    def _add_returns(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add return-based features."""
        if 'close' not in df.columns:
            return df

        # Simple returns (shifted to be available at decision time)
        df['return_1'] = df['close'].pct_change(1).shift(1)
        df['return_5'] = df['close'].pct_change(5).shift(1)
        df['return_10'] = df['close'].pct_change(10).shift(1)
        df['return_20'] = df['close'].pct_change(20).shift(1)

        # Log returns
        df['log_return_1'] = np.log(df['close'] / df['close'].shift(1)).shift(1)

        return df

    def _add_volatility(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add volatility features."""
        if 'close' not in df.columns:
            return df

        # Rolling volatility (shifted)
        returns = df['close'].pct_change()
        df['volatility_10'] = returns.rolling(10).std().shift(1)
        df['volatility_20'] = returns.rolling(20).std().shift(1)

        # ATR (Average True Range)
        if all(col in df.columns for col in ['high', 'low', 'close']):
            high_low = df['high'] - df['low']
            high_close = abs(df['high'] - df['close'].shift(1))
            low_close = abs(df['low'] - df['close'].shift(1))
            true_range = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
            df['atr_14'] = true_range.rolling(14).mean().shift(1)

        # Normalized ATR
        if 'atr_14' in df.columns:
            df['atr_pct'] = (df['atr_14'] / df['close'].shift(1)) * 100

        return df

    def _add_momentum(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add momentum indicators."""
        if 'close' not in df.columns:
            return df

        # RSI
        df['rsi_14'] = self._calculate_rsi(df['close'], 14).shift(1)

        # MACD
        ema_12 = df['close'].ewm(span=12, adjust=False).mean()
        ema_26 = df['close'].ewm(span=26, adjust=False).mean()
        df['macd'] = (ema_12 - ema_26).shift(1)
        df['macd_signal'] = df['macd'].ewm(span=9, adjust=False).mean()
        df['macd_hist'] = df['macd'] - df['macd_signal']

        # Rate of Change
        df['roc_10'] = ((df['close'] - df['close'].shift(10)) / df['close'].shift(10) * 100).shift(1)

        # Moving average crossovers
        df['sma_10'] = df['close'].rolling(10).mean().shift(1)
        df['sma_20'] = df['close'].rolling(20).mean().shift(1)
        df['sma_50'] = df['close'].rolling(50).mean().shift(1)

        df['ema_10'] = df['close'].ewm(span=10, adjust=False).mean().shift(1)
        df['ema_20'] = df['close'].ewm(span=20, adjust=False).mean().shift(1)

        # Price relative to moving averages
        df['price_sma_10_ratio'] = (df['close'].shift(1) / df['sma_10'])
        df['price_sma_20_ratio'] = (df['close'].shift(1) / df['sma_20'])

        return df

    def _add_volume_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add volume-based features."""
        if 'volume' not in df.columns:
            return df

        # Volume moving averages (shifted)
        df['volume_sma_10'] = df['volume'].rolling(10).mean().shift(1)
        df['volume_sma_20'] = df['volume'].rolling(20).mean().shift(1)

        # Volume ratio
        df['volume_ratio'] = (df['volume'].shift(1) / df['volume_sma_20'])

        # On-Balance Volume (simplified)
        obv_direction = np.where(df['close'] > df['close'].shift(1), 1,
                                 np.where(df['close'] < df['close'].shift(1), -1, 0))
        df['obv'] = (obv_direction * df['volume']).cumsum().shift(1)

        # Volume-weighted price
        if 'close' in df.columns:
            df['vwap'] = (df['close'] * df['volume']).rolling(20).sum().shift(1) / \
                         df['volume'].rolling(20).sum().shift(1)

        return df

    def _add_price_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Add price-based features."""
        if not all(col in df.columns for col in ['high', 'low', 'close']):
            return df

        # Bollinger Bands
        sma_20 = df['close'].rolling(20).mean()
        std_20 = df['close'].rolling(20).std()
        df['bb_upper'] = (sma_20 + 2 * std_20).shift(1)
        df['bb_lower'] = (sma_20 - 2 * std_20).shift(1)
        df['bb_width'] = ((df['bb_upper'] - df['bb_lower']) / sma_20.shift(1))
        df['bb_position'] = ((df['close'].shift(1) - df['bb_lower']) /
                            (df['bb_upper'] - df['bb_lower']))

        # High/Low range
        df['range_pct'] = ((df['high'] - df['low']) / df['close'] * 100).shift(1)

        # Distance from high/low
        df['high_20'] = df['high'].rolling(20).max().shift(1)
        df['low_20'] = df['low'].rolling(20).min().shift(1)
        df['dist_from_high'] = ((df['high_20'] - df['close'].shift(1)) / df['high_20'] * 100)
        df['dist_from_low'] = ((df['close'].shift(1) - df['low_20']) / df['low_20'] * 100)

        return df

    def _add_custom_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Add strategy-specific custom features.

        Override this method to add features specific to your strategy.
        Remember to use .shift(1) to prevent lookahead bias!

        Args:
            df: DataFrame with existing features

        Returns:
            DataFrame with custom features added
        """
        # Example custom features (customize based on strategy)

        # Feature from params
        # lookback = self.params.get('custom_lookback', 10)
        # df['custom_feature'] = df['close'].rolling(lookback).mean().shift(1)

        return df

    def _calculate_rsi(self, prices: pd.Series, period: int = 14) -> pd.Series:
        """Calculate RSI indicator."""
        delta = prices.diff()

        gain = delta.where(delta > 0, 0)
        loss = -delta.where(delta < 0, 0)

        avg_gain = gain.rolling(window=period).mean()
        avg_loss = loss.rolling(window=period).mean()

        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))

        return rsi

    def _validate_no_lookahead(self, df: pd.DataFrame) -> bool:
        """
        Validate that features don't have lookahead bias.

        This is a basic check - it verifies that feature values at index t
        are not correlated with future returns.

        Args:
            df: DataFrame with features

        Returns:
            True if validation passes
        """
        if len(df) < 100:
            return True  # Not enough data to validate

        # Check correlation of features with future returns
        if 'close' in df.columns:
            future_return = df['close'].pct_change().shift(-1)  # Next bar return

            suspicious_features = []
            for col in df.columns:
                if col == 'close' or df[col].dtype not in ['float64', 'int64']:
                    continue

                # High correlation with future returns is suspicious
                corr = df[col].corr(future_return)
                if abs(corr) > 0.5:  # Threshold for suspicion
                    suspicious_features.append((col, corr))

            if suspicious_features:
                warnings.warn(
                    f"Potential lookahead bias detected in features: {suspicious_features}"
                )
                return False

        return True

    def get_feature_names(self) -> List[str]:
        """Get list of feature names that will be generated."""
        return [
            'return_1', 'return_5', 'return_10', 'return_20', 'log_return_1',
            'volatility_10', 'volatility_20', 'atr_14', 'atr_pct',
            'rsi_14', 'macd', 'macd_signal', 'macd_hist', 'roc_10',
            'sma_10', 'sma_20', 'sma_50', 'ema_10', 'ema_20',
            'price_sma_10_ratio', 'price_sma_20_ratio',
            'volume_sma_10', 'volume_sma_20', 'volume_ratio', 'obv', 'vwap',
            'bb_upper', 'bb_lower', 'bb_width', 'bb_position',
            'range_pct', 'high_20', 'low_20', 'dist_from_high', 'dist_from_low'
        ]


# For direct testing
if __name__ == "__main__":
    # Create sample data
    np.random.seed(42)
    dates = pd.date_range('2024-01-01', periods=1000, freq='h')
    data = pd.DataFrame({
        'open': 100 + np.cumsum(np.random.randn(1000) * 0.5),
        'high': 0,
        'low': 0,
        'close': 0,
        'volume': np.random.randint(1000, 10000, 1000)
    }, index=dates)

    data['close'] = data['open'] + np.random.randn(1000) * 0.3
    data['high'] = data[['open', 'close']].max(axis=1) + abs(np.random.randn(1000) * 0.2)
    data['low'] = data[['open', 'close']].min(axis=1) - abs(np.random.randn(1000) * 0.2)

    # Generate features
    generator = FeatureGenerator({})
    features = generator.generate(data)

    print(f"Generated {len(features.columns)} columns")
    print(f"Features shape: {features.shape}")
    print(f"\nFeature columns: {list(features.columns)}")
