"""
Signal Generation for {strategy_name}
Generated by CBT Framework

Trading signal logic based on features.
"""

import pandas as pd
import numpy as np
from dataclasses import dataclass
from typing import Optional, Dict, Any, List
from enum import Enum


class SignalDirection(Enum):
    """Signal direction enum."""
    LONG = 1
    SHORT = -1
    FLAT = 0


@dataclass
class Signal:
    """
    Trading signal with direction and metadata.

    Attributes:
        direction: 1 for long, -1 for short, 0 for no signal
        confidence: Signal strength from 0.0 to 1.0
        metadata: Optional dictionary with additional signal info
    """
    direction: int  # 1 = long, -1 = short, 0 = flat
    confidence: float  # 0.0 to 1.0
    metadata: Optional[Dict[str, Any]] = None

    def __post_init__(self):
        # Validate direction
        if self.direction not in [-1, 0, 1]:
            raise ValueError(f"Direction must be -1, 0, or 1, got {self.direction}")

        # Clamp confidence
        self.confidence = max(0.0, min(1.0, self.confidence))


class SignalGenerator:
    """
    Generate trading signals from features.

    This class implements the entry logic defined in DISCOVERY.md.
    Signals are generated based on feature values at each timestamp.

    Usage:
        generator = SignalGenerator(params)
        signal = generator.generate(features, idx)
    """

    def __init__(self, params: dict):
        """
        Initialize signal generator.

        Args:
            params: Strategy parameters from config
        """
        self.params = params

        # Signal thresholds (customize based on strategy)
        self.rsi_oversold = params.get('rsi_oversold', 30)
        self.rsi_overbought = params.get('rsi_overbought', 70)
        self.trend_strength = params.get('trend_strength', 0.02)
        self.min_confidence = params.get('min_confidence', 0.5)

    def generate(self, features: pd.DataFrame, idx: int) -> Signal:
        """
        Generate signal for given index.

        IMPORTANT: Only use data available at time idx.
        The features DataFrame should already be shifted to prevent lookahead.

        Args:
            features: DataFrame with calculated features
            idx: Current index to generate signal for

        Returns:
            Signal object with direction and confidence
        """
        if idx < 0 or idx >= len(features):
            return Signal(direction=0, confidence=0.0)

        row = features.iloc[idx]

        # Get signal components
        trend_signal = self._get_trend_signal(row)
        momentum_signal = self._get_momentum_signal(row)
        volume_signal = self._get_volume_signal(row)

        # Combine signals
        direction, confidence = self._combine_signals(
            trend_signal, momentum_signal, volume_signal
        )

        # Apply minimum confidence filter
        if confidence < self.min_confidence:
            direction = 0
            confidence = 0.0

        return Signal(
            direction=direction,
            confidence=confidence,
            metadata={
                'trend': trend_signal,
                'momentum': momentum_signal,
                'volume': volume_signal,
                'idx': idx
            }
        )

    def _get_trend_signal(self, row: pd.Series) -> float:
        """
        Calculate trend signal component.

        Returns:
            Float from -1 (bearish) to 1 (bullish)
        """
        signal = 0.0

        # Moving average trend
        if 'sma_10' in row.index and 'sma_20' in row.index:
            if pd.notna(row['sma_10']) and pd.notna(row['sma_20']):
                ma_ratio = row['sma_10'] / row['sma_20']
                if ma_ratio > 1 + self.trend_strength:
                    signal += 0.5
                elif ma_ratio < 1 - self.trend_strength:
                    signal -= 0.5

        # Price vs SMA
        if 'price_sma_20_ratio' in row.index:
            if pd.notna(row['price_sma_20_ratio']):
                if row['price_sma_20_ratio'] > 1.02:
                    signal += 0.3
                elif row['price_sma_20_ratio'] < 0.98:
                    signal -= 0.3

        # MACD
        if 'macd_hist' in row.index:
            if pd.notna(row['macd_hist']):
                if row['macd_hist'] > 0:
                    signal += 0.2
                else:
                    signal -= 0.2

        return max(-1.0, min(1.0, signal))

    def _get_momentum_signal(self, row: pd.Series) -> float:
        """
        Calculate momentum signal component.

        Returns:
            Float from -1 (oversold/reversal up) to 1 (overbought/reversal down)
        """
        signal = 0.0

        # RSI
        if 'rsi_14' in row.index and pd.notna(row['rsi_14']):
            rsi = row['rsi_14']
            if rsi < self.rsi_oversold:
                signal += (self.rsi_oversold - rsi) / self.rsi_oversold
            elif rsi > self.rsi_overbought:
                signal -= (rsi - self.rsi_overbought) / (100 - self.rsi_overbought)

        # ROC
        if 'roc_10' in row.index and pd.notna(row['roc_10']):
            roc = row['roc_10']
            signal += np.clip(roc / 10, -0.3, 0.3)

        return max(-1.0, min(1.0, signal))

    def _get_volume_signal(self, row: pd.Series) -> float:
        """
        Calculate volume signal component.

        Returns:
            Float from 0 (low volume) to 1 (high volume confirmation)
        """
        if 'volume_ratio' not in row.index:
            return 0.5  # Neutral if no volume data

        if pd.isna(row['volume_ratio']):
            return 0.5

        vol_ratio = row['volume_ratio']

        # High volume confirms moves
        if vol_ratio > 1.5:
            return 1.0
        elif vol_ratio > 1.0:
            return 0.7
        elif vol_ratio > 0.5:
            return 0.5
        else:
            return 0.3

    def _combine_signals(self, trend: float, momentum: float,
                         volume: float) -> tuple:
        """
        Combine signal components into final direction and confidence.

        Args:
            trend: Trend signal (-1 to 1)
            momentum: Momentum signal (-1 to 1)
            volume: Volume signal (0 to 1)

        Returns:
            Tuple of (direction, confidence)
        """
        # Weighted combination
        weights = self.params.get('signal_weights', {
            'trend': 0.5,
            'momentum': 0.3,
            'volume': 0.2
        })

        # Combined signal strength
        raw_signal = (
            trend * weights.get('trend', 0.5) +
            momentum * weights.get('momentum', 0.3)
        )

        # Volume as confidence multiplier
        volume_mult = 0.5 + (volume * 0.5)  # Maps 0-1 to 0.5-1.0

        # Determine direction
        if raw_signal > 0.2:
            direction = 1
        elif raw_signal < -0.2:
            direction = -1
        else:
            direction = 0

        # Calculate confidence
        confidence = abs(raw_signal) * volume_mult

        return direction, confidence

    def generate_all(self, features: pd.DataFrame) -> pd.DataFrame:
        """
        Generate signals for entire dataset.

        Args:
            features: DataFrame with calculated features

        Returns:
            DataFrame with signal columns
        """
        signals = []

        for idx in range(len(features)):
            signal = self.generate(features, idx)
            signals.append({
                'direction': signal.direction,
                'confidence': signal.confidence
            })

        result = pd.DataFrame(signals, index=features.index)

        # Add signal change detection
        result['signal_change'] = result['direction'].diff().fillna(0).astype(int)

        return result


# For direct testing
if __name__ == "__main__":
    from features import FeatureGenerator

    # Create sample data
    np.random.seed(42)
    dates = pd.date_range('2024-01-01', periods=500, freq='h')
    data = pd.DataFrame({
        'open': 100 + np.cumsum(np.random.randn(500) * 0.5),
        'high': 0,
        'low': 0,
        'close': 0,
        'volume': np.random.randint(1000, 10000, 500)
    }, index=dates)

    data['close'] = data['open'] + np.random.randn(500) * 0.3
    data['high'] = data[['open', 'close']].max(axis=1) + abs(np.random.randn(500) * 0.2)
    data['low'] = data[['open', 'close']].min(axis=1) - abs(np.random.randn(500) * 0.2)

    # Generate features
    feature_gen = FeatureGenerator({})
    features = feature_gen.generate(data)

    # Generate signals
    signal_gen = SignalGenerator({})
    signals = signal_gen.generate_all(features)

    print(f"Total signals generated: {len(signals)}")
    print(f"\nSignal distribution:")
    print(signals['direction'].value_counts())

    print(f"\nAverage confidence by direction:")
    print(signals.groupby('direction')['confidence'].mean())
