"""
Backtest Runner
Generated by CBT Framework

Usage:
    python backtest.py
    python backtest.py --config custom_config.yaml
    python backtest.py --output experiments/exp_001.yaml
"""

import argparse
import yaml
import pandas as pd
import numpy as np
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, asdict

from strategy import Strategy, Position


@dataclass
class Trade:
    """Completed trade record."""
    entry_time: str
    exit_time: str
    direction: int
    entry_price: float
    exit_price: float
    size: float
    pnl: float
    pnl_percent: float
    exit_reason: str
    duration_seconds: int
    fees: float


@dataclass
class BacktestResults:
    """Complete backtest results."""
    # Metadata
    strategy_name: str
    start_date: str
    end_date: str
    initial_capital: float
    final_equity: float

    # Performance metrics
    total_return: float
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    max_drawdown_duration: int  # in bars

    # Trade metrics
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: float
    profit_factor: float
    avg_trade: float
    avg_winner: float
    avg_loser: float
    largest_winner: float
    largest_loser: float
    avg_duration_seconds: int
    max_consecutive_wins: int
    max_consecutive_losses: int

    # Risk metrics
    calmar_ratio: float
    avg_drawdown: float

    # Prop firm metrics (None if not enabled)
    prop_firm_compliant: Optional[bool] = None
    prop_firm_max_dd_from_initial: Optional[float] = None
    prop_firm_daily_loss_breaches: Optional[int] = None
    prop_firm_breach_bar: Optional[int] = None
    prop_firm_breach_reason: Optional[str] = None
    prop_firm_target_reached: Optional[bool] = None
    prop_firm_target_bar: Optional[int] = None


class BacktestEngine:
    """
    Event-driven backtest engine.

    Features:
    - Realistic fee modeling
    - Slippage simulation
    - Position tracking
    - Equity curve generation
    """

    def __init__(self, strategy: Strategy, config: dict):
        self.strategy = strategy
        self.config = config

        # Account state
        self.initial_capital = config['account']['initial_capital']
        self.equity = self.initial_capital
        self.cash = self.initial_capital

        # Position tracking
        self.position: Optional[Position] = None
        self.max_positions = config['sizing']['max_positions']

        # Trade history
        self.trades: List[Trade] = []
        self.equity_curve: List[float] = []

        # Fee configuration
        self.maker_fee = config['fees']['maker'] / 100
        self.taker_fee = config['fees']['taker'] / 100
        self.slippage = config['fees']['slippage'] / 100

        # Prop firm challenge tracking
        pf = config.get('prop_firm', {})
        self.prop_firm_enabled = pf.get('enabled', False)
        if self.prop_firm_enabled:
            self.pf_max_drawdown_pct = pf.get('max_drawdown_percent', 10.0)
            self.pf_daily_loss_pct = pf.get('daily_loss_percent', 5.0)
            phase = pf.get('phase', 1)
            self.pf_target_pct = pf.get(f'phase{phase}_target_percent', 10.0)
            self.pf_breach_action = pf.get('breach_action', 'halt')
        else:
            self.pf_max_drawdown_pct = 10.0
            self.pf_daily_loss_pct = 5.0
            self.pf_target_pct = 10.0
            self.pf_breach_action = 'halt'

        # Prop firm runtime state
        self.pf_halted = False
        self.pf_breach_bar = None
        self.pf_breach_reason = None
        self.pf_prev_day_equity = self.initial_capital
        self.pf_current_day = None
        self.pf_daily_loss_breach_bars = []
        self.pf_target_bar = None

    def calculate_fees(self, price: float, size: float, order_type: str = 'taker') -> float:
        """Calculate trading fees."""
        notional = price * size
        fee_rate = self.taker_fee if order_type == 'taker' else self.maker_fee
        return notional * fee_rate

    def apply_slippage(self, price: float, direction: int, is_entry: bool) -> float:
        """Apply slippage to price."""
        # Entry: slippage works against us
        # Exit: slippage works against us
        if is_entry:
            if direction == 1:  # Long entry - price goes up
                return price * (1 + self.slippage)
            else:  # Short entry - price goes down
                return price * (1 - self.slippage)
        else:
            if direction == 1:  # Long exit - price goes down
                return price * (1 - self.slippage)
            else:  # Short exit - price goes up
                return price * (1 + self.slippage)

    def open_position(self, timestamp: pd.Timestamp, price: float,
                      direction: int, size: float) -> Position:
        """Open a new position."""
        # Apply slippage
        entry_price = self.apply_slippage(price, direction, is_entry=True)

        # Calculate fees
        fees = self.calculate_fees(entry_price, size)
        self.cash -= fees

        # Calculate stop loss and take profit
        stop_loss = self.strategy.calculate_stop_loss(entry_price, direction)
        take_profit = self.strategy.calculate_take_profit(entry_price, direction, stop_loss)

        position = Position(
            entry_time=timestamp,
            entry_price=entry_price,
            direction=direction,
            size=size,
            stop_loss=stop_loss,
            take_profit=take_profit,
            highest_price=entry_price,
            lowest_price=entry_price
        )

        return position

    def close_position(self, position: Position, timestamp: pd.Timestamp,
                       price: float, exit_reason: str) -> Trade:
        """Close position and record trade."""
        # Apply slippage
        exit_price = self.apply_slippage(price, position.direction, is_entry=False)

        # Calculate PnL
        if position.direction == 1:  # Long
            pnl = (exit_price - position.entry_price) * position.size
        else:  # Short
            pnl = (position.entry_price - exit_price) * position.size

        # Calculate fees
        fees = self.calculate_fees(exit_price, position.size)
        pnl -= fees

        # Update equity
        self.equity += pnl

        # Calculate duration
        duration = int((timestamp - position.entry_time).total_seconds())

        # Create trade record
        trade = Trade(
            entry_time=str(position.entry_time),
            exit_time=str(timestamp),
            direction=position.direction,
            entry_price=position.entry_price,
            exit_price=exit_price,
            size=position.size,
            pnl=pnl,
            pnl_percent=(pnl / (position.entry_price * position.size)) * 100,
            exit_reason=exit_reason,
            duration_seconds=duration,
            fees=fees
        )

        self.trades.append(trade)
        return trade

    def run(self) -> BacktestResults:
        """Execute the backtest."""
        # Initialize strategy and get features
        features = self.strategy.initialize()

        # Get price column
        price_col = 'close' if 'close' in features.columns else features.columns[0]

        # Main loop
        for idx in range(len(features)):
            current = features.iloc[idx]
            timestamp = features.index[idx]
            current_price = current[price_col]

            # --- Prop firm: detect new day and update prev day equity ---
            if self.prop_firm_enabled:
                try:
                    bar_date = pd.Timestamp(timestamp).date()
                except Exception:
                    bar_date = None

                if bar_date is not None:
                    if self.pf_current_day is None:
                        self.pf_current_day = bar_date
                    elif bar_date != self.pf_current_day:
                        # New day: snapshot previous day's closing equity
                        self.pf_prev_day_equity = self.equity_curve[-1] if self.equity_curve else self.equity
                        self.pf_current_day = bar_date

            # Check exits first
            if self.position is not None:
                # Prop firm breach: force close position
                if self.prop_firm_enabled and self.pf_halted:
                    self.close_position(self.position, timestamp, current_price, 'prop_firm_breach')
                    self.position = None
                else:
                    exit_reason = self.strategy.check_exit(
                        self.position, current_price, idx
                    )
                    if exit_reason:
                        self.close_position(self.position, timestamp, current_price, exit_reason)
                        self.position = None

            # Check entries (skip if prop firm halted)
            if self.position is None and not (self.prop_firm_enabled and self.pf_halted):
                signal = self.strategy.get_signal(idx)

                if signal.direction != 0:
                    size = self.strategy.calculate_position_size(
                        signal, self.equity, current_price
                    )

                    # Check if we have enough capital
                    required_margin = current_price * size
                    if self.config['leverage']['enabled']:
                        required_margin /= self.config['leverage']['default']

                    if required_margin <= self.equity:
                        self.position = self.open_position(
                            timestamp, current_price, signal.direction, size
                        )

            # Record equity (mark-to-market if position open)
            if self.position:
                if self.position.direction == 1:
                    unrealized = (current_price - self.position.entry_price) * self.position.size
                else:
                    unrealized = (self.position.entry_price - current_price) * self.position.size
                self.equity_curve.append(self.equity + unrealized)
            else:
                self.equity_curve.append(self.equity)

            # --- Prop firm: check drawdown and daily loss after equity update ---
            if self.prop_firm_enabled and not self.pf_halted:
                current_equity = self.equity_curve[-1]

                # Check max drawdown from initial capital
                dd_from_initial = (current_equity - self.initial_capital) / self.initial_capital * 100
                if dd_from_initial <= -self.pf_max_drawdown_pct:
                    self.pf_halted = True
                    self.pf_breach_bar = idx
                    self.pf_breach_reason = f'max_drawdown ({dd_from_initial:.2f}% <= -{self.pf_max_drawdown_pct}%)'

                # Check daily loss from previous day equity
                if self.pf_prev_day_equity > 0:
                    daily_loss = (current_equity - self.pf_prev_day_equity) / self.pf_prev_day_equity * 100
                    if daily_loss <= -self.pf_daily_loss_pct:
                        self.pf_daily_loss_breach_bars.append(idx)
                        if not self.pf_halted:
                            self.pf_halted = True
                            self.pf_breach_bar = idx
                            self.pf_breach_reason = f'daily_loss ({daily_loss:.2f}% <= -{self.pf_daily_loss_pct}%)'

                # Check target reached
                if self.pf_target_bar is None:
                    profit_pct = (current_equity - self.initial_capital) / self.initial_capital * 100
                    if profit_pct >= self.pf_target_pct:
                        self.pf_target_bar = idx

        # Close any remaining position
        if self.position is not None:
            final_price = features.iloc[-1][price_col]
            self.close_position(self.position, features.index[-1], final_price, 'end')
            self.position = None

        # Calculate results
        return self._calculate_results(features)

    def _calculate_results(self, features: pd.DataFrame) -> BacktestResults:
        """Calculate all performance metrics."""
        equity_series = pd.Series(self.equity_curve)

        # Returns
        returns = equity_series.pct_change().dropna()
        total_return = (self.equity - self.initial_capital) / self.initial_capital * 100

        # Sharpe ratio (assuming daily for simplicity, adjust as needed)
        if len(returns) > 1 and returns.std() > 0:
            sharpe = returns.mean() / returns.std() * np.sqrt(252 * 24)  # Hourly data assumption
        else:
            sharpe = 0.0

        # Sortino ratio
        negative_returns = returns[returns < 0]
        if len(negative_returns) > 1 and negative_returns.std() > 0:
            sortino = returns.mean() / negative_returns.std() * np.sqrt(252 * 24)
        else:
            sortino = 0.0

        # Drawdown analysis
        rolling_max = equity_series.expanding().max()
        drawdown = (equity_series - rolling_max) / rolling_max * 100
        max_drawdown = drawdown.min()

        # Max drawdown duration
        in_drawdown = drawdown < 0
        drawdown_groups = (in_drawdown != in_drawdown.shift()).cumsum()
        if in_drawdown.any():
            max_dd_duration = in_drawdown.groupby(drawdown_groups).sum().max()
        else:
            max_dd_duration = 0

        # Trade statistics
        if self.trades:
            pnls = [t.pnl for t in self.trades]
            winners = [t for t in self.trades if t.pnl > 0]
            losers = [t for t in self.trades if t.pnl <= 0]

            win_rate = len(winners) / len(self.trades) * 100 if self.trades else 0

            gross_profit = sum(t.pnl for t in winners) if winners else 0
            gross_loss = abs(sum(t.pnl for t in losers)) if losers else 1
            profit_factor = gross_profit / gross_loss if gross_loss > 0 else float('inf')

            avg_trade = np.mean(pnls) if pnls else 0
            avg_winner = np.mean([t.pnl for t in winners]) if winners else 0
            avg_loser = np.mean([t.pnl for t in losers]) if losers else 0
            largest_winner = max(pnls) if pnls else 0
            largest_loser = min(pnls) if pnls else 0

            durations = [t.duration_seconds for t in self.trades]
            avg_duration = int(np.mean(durations)) if durations else 0

            # Consecutive wins/losses
            outcomes = [1 if t.pnl > 0 else 0 for t in self.trades]
            max_consecutive_wins = self._max_consecutive(outcomes, 1)
            max_consecutive_losses = self._max_consecutive(outcomes, 0)
        else:
            win_rate = 0
            profit_factor = 0
            avg_trade = 0
            avg_winner = 0
            avg_loser = 0
            largest_winner = 0
            largest_loser = 0
            avg_duration = 0
            max_consecutive_wins = 0
            max_consecutive_losses = 0
            winners = []
            losers = []

        # Calmar ratio
        calmar = abs(total_return / max_drawdown) if max_drawdown != 0 else 0

        # Average drawdown
        avg_drawdown = drawdown[drawdown < 0].mean() if (drawdown < 0).any() else 0

        # Prop firm metrics
        pf_compliant = None
        pf_max_dd = None
        pf_daily_breaches = None
        pf_breach_bar = None
        pf_breach_reason = None
        pf_target_reached = None
        pf_target_bar = None

        if self.prop_firm_enabled:
            equity_arr = equity_series.values
            dd_from_initial = (equity_arr - self.initial_capital) / self.initial_capital * 100
            pf_max_dd = round(float(dd_from_initial.min()), 2)
            pf_daily_breaches = len(self.pf_daily_loss_breach_bars)
            pf_breach_bar = self.pf_breach_bar
            pf_breach_reason = self.pf_breach_reason
            pf_target_reached = self.pf_target_bar is not None
            pf_target_bar = self.pf_target_bar
            pf_compliant = not self.pf_halted

        return BacktestResults(
            strategy_name=self.strategy.config.get('strategy_name', 'unnamed'),
            start_date=str(features.index[0]),
            end_date=str(features.index[-1]),
            initial_capital=self.initial_capital,
            final_equity=self.equity,
            total_return=round(total_return, 2),
            sharpe_ratio=round(sharpe, 2),
            sortino_ratio=round(sortino, 2),
            max_drawdown=round(max_drawdown, 2),
            max_drawdown_duration=int(max_dd_duration),
            total_trades=len(self.trades),
            winning_trades=len(winners),
            losing_trades=len(losers),
            win_rate=round(win_rate, 2),
            profit_factor=round(profit_factor, 2),
            avg_trade=round(avg_trade, 2),
            avg_winner=round(avg_winner, 2),
            avg_loser=round(avg_loser, 2),
            largest_winner=round(largest_winner, 2),
            largest_loser=round(largest_loser, 2),
            avg_duration_seconds=avg_duration,
            max_consecutive_wins=max_consecutive_wins,
            max_consecutive_losses=max_consecutive_losses,
            calmar_ratio=round(calmar, 2),
            avg_drawdown=round(avg_drawdown, 2),
            prop_firm_compliant=pf_compliant,
            prop_firm_max_dd_from_initial=pf_max_dd,
            prop_firm_daily_loss_breaches=pf_daily_breaches,
            prop_firm_breach_bar=pf_breach_bar,
            prop_firm_breach_reason=pf_breach_reason,
            prop_firm_target_reached=pf_target_reached,
            prop_firm_target_bar=pf_target_bar,
        )

    def _max_consecutive(self, outcomes: List[int], target: int) -> int:
        """Find maximum consecutive occurrences of target."""
        max_count = 0
        current_count = 0
        for outcome in outcomes:
            if outcome == target:
                current_count += 1
                max_count = max(max_count, current_count)
            else:
                current_count = 0
        return max_count

    def save_results(self, results: BacktestResults, output_path: str):
        """Save backtest results to YAML."""
        output = {
            'metadata': {
                'timestamp': datetime.now().isoformat(),
                'strategy': results.strategy_name,
            },
            'parameters': self.config,
            'results': asdict(results),
        }

        with open(output_path, 'w') as f:
            yaml.dump(output, f, default_flow_style=False, sort_keys=False)

    def save_trades(self, output_path: str):
        """Save trade log to CSV."""
        if not self.trades:
            return

        df = pd.DataFrame([asdict(t) for t in self.trades])
        df.to_csv(output_path, index=False)

    def save_equity_curve(self, output_path: str):
        """Save equity curve to CSV."""
        df = pd.DataFrame({'equity': self.equity_curve})
        df.to_csv(output_path, index=False)


def main():
    parser = argparse.ArgumentParser(description='Run backtest')
    parser.add_argument('--config', default='config.yaml', help='Config file path')
    parser.add_argument('--output', help='Output YAML path')
    parser.add_argument('--trades', help='Trades CSV output path')
    parser.add_argument('--equity', help='Equity curve CSV output path')
    args = parser.parse_args()

    # Load config
    with open(args.config) as f:
        config = yaml.safe_load(f)

    # Initialize strategy and engine
    strategy = Strategy(config)
    engine = BacktestEngine(strategy, config)

    # Run backtest
    print("Running backtest...")
    results = engine.run()

    # Display results
    print("\n" + "=" * 60)
    print("BACKTEST RESULTS")
    print("=" * 60)
    print(f"\nPerformance:")
    print(f"  Total Return:  {results.total_return:+.2f}%")
    print(f"  Sharpe Ratio:  {results.sharpe_ratio:.2f}")
    print(f"  Sortino Ratio: {results.sortino_ratio:.2f}")
    print(f"  Max Drawdown:  {results.max_drawdown:.2f}%")
    print(f"\nTrades:")
    print(f"  Total:         {results.total_trades}")
    print(f"  Win Rate:      {results.win_rate:.1f}%")
    print(f"  Profit Factor: {results.profit_factor:.2f}")
    print(f"  Avg Winner:    ${results.avg_winner:.2f}")
    print(f"  Avg Loser:     ${results.avg_loser:.2f}")

    if results.prop_firm_compliant is not None:
        status = "PASS" if results.prop_firm_compliant else "FAIL"
        print(f"\nProp Firm Compliance: {status}")
        print(f"  Max DD from initial: {results.prop_firm_max_dd_from_initial:.2f}%")
        print(f"  Daily loss breaches: {results.prop_firm_daily_loss_breaches}")
        target_str = "Yes" if results.prop_firm_target_reached else "No"
        if results.prop_firm_target_bar is not None:
            target_str += f" (bar {results.prop_firm_target_bar})"
        print(f"  Target reached:      {target_str}")
        if results.prop_firm_breach_reason:
            print(f"  Breach reason:       {results.prop_firm_breach_reason}")

    print("=" * 60)

    # Save outputs
    if args.output:
        engine.save_results(results, args.output)
        print(f"\nResults saved to: {args.output}")

    if args.trades:
        engine.save_trades(args.trades)
        print(f"Trades saved to: {args.trades}")

    if args.equity:
        engine.save_equity_curve(args.equity)
        print(f"Equity curve saved to: {args.equity}")

    return results


if __name__ == "__main__":
    main()
