"""
Strategy: {strategy_name}
Generated by CBT Framework

{strategy_description}
"""

import pandas as pd
import numpy as np
from typing import Optional, Dict, Any, List
from dataclasses import dataclass, field
from pathlib import Path

# Import generated modules
from src.data_loader import DataLoader
from src.features import FeatureGenerator
from src.signals import SignalGenerator, Signal


@dataclass
class Position:
    """Represents an open position."""
    entry_time: pd.Timestamp
    entry_price: float
    direction: int  # 1 = long, -1 = short
    size: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop_price: Optional[float] = None
    highest_price: float = 0.0  # For trailing stop
    lowest_price: float = float('inf')  # For trailing stop (short)


class Strategy:
    """
    {strategy_name}

    Entry: {entry_conditions}
    Exit: {exit_conditions}
    """

    def __init__(self, config: dict):
        """
        Initialize strategy with configuration.

        Args:
            config: Configuration dictionary from config.yaml
        """
        self.config = config
        self.params = config.get('strategy_params', {})

        # Initialize components
        self.data_loader = DataLoader()
        self.feature_gen = FeatureGenerator(self.params)
        self.signal_gen = SignalGenerator(self.params)

        # State
        self.data: Optional[pd.DataFrame] = None
        self.features: Optional[pd.DataFrame] = None

    def initialize(self) -> pd.DataFrame:
        """
        Load data and generate features.

        Returns:
            DataFrame with features ready for backtesting
        """
        # Load all data
        self.data = self.data_loader.load_all()

        # Get time-aligned data
        start = self.config['time'].get('start_date')
        end = self.config['time'].get('end_date')
        aligned = self.data_loader.get_aligned(start=start, end=end)

        # Generate features
        self.features = self.feature_gen.generate(aligned)

        return self.features

    def get_signal(self, idx: int) -> Signal:
        """
        Get trading signal for given index.

        Args:
            idx: Index in the features DataFrame

        Returns:
            Signal object with direction and confidence
        """
        if self.features is None:
            raise RuntimeError("Strategy not initialized. Call initialize() first.")

        return self.signal_gen.generate(self.features, idx)

    def calculate_position_size(self, signal: Signal,
                                equity: float,
                                price: float) -> float:
        """
        Calculate position size based on config and signal.

        Args:
            signal: Trading signal
            equity: Current account equity
            price: Current price

        Returns:
            Position size in base currency
        """
        sizing = self.config['sizing']
        leverage_config = self.config['leverage']

        # Calculate base risk amount
        if sizing['mode'] == 'percent':
            risk_amount = equity * (sizing['percent_per_trade'] / 100)
        elif sizing['mode'] == 'fixed':
            risk_amount = min(sizing['fixed_amount'], equity)
        else:  # kelly
            # Quarter Kelly for safety
            risk_amount = equity * signal.confidence * 0.25

        # Apply leverage if enabled
        if leverage_config['enabled']:
            leverage = min(leverage_config['default'], leverage_config['max'])
            risk_amount *= leverage

        # Convert to position size
        position_size = risk_amount / price

        return position_size

    def calculate_stop_loss(self, entry_price: float,
                           direction: int,
                           atr: Optional[float] = None) -> Optional[float]:
        """
        Calculate stop loss price.

        Args:
            entry_price: Entry price of the position
            direction: 1 for long, -1 for short
            atr: ATR value if using ATR-based stops

        Returns:
            Stop loss price or None if disabled
        """
        sl_config = self.config['risk']['stop_loss']

        if not sl_config['enabled']:
            return None

        if sl_config['mode'] == 'percent':
            pct = sl_config['percent'] / 100
            if direction == 1:  # long
                return entry_price * (1 - pct)
            else:  # short
                return entry_price * (1 + pct)

        elif sl_config['mode'] == 'atr' and atr is not None:
            multiplier = sl_config.get('atr_multiplier', 2.0)
            if direction == 1:
                return entry_price - (atr * multiplier)
            else:
                return entry_price + (atr * multiplier)

        elif sl_config['mode'] == 'fixed':
            fixed = sl_config['fixed_value']
            if direction == 1:
                return entry_price - fixed
            else:
                return entry_price + fixed

        return None

    def calculate_take_profit(self, entry_price: float,
                             direction: int,
                             stop_loss: Optional[float] = None) -> Optional[float]:
        """
        Calculate take profit price.

        Args:
            entry_price: Entry price of the position
            direction: 1 for long, -1 for short
            stop_loss: Stop loss price for R:R calculation

        Returns:
            Take profit price or None if disabled
        """
        tp_config = self.config['risk']['take_profit']

        if not tp_config['enabled']:
            return None

        if tp_config['mode'] == 'percent':
            pct = tp_config['percent'] / 100
            if direction == 1:  # long
                return entry_price * (1 + pct)
            else:  # short
                return entry_price * (1 - pct)

        elif tp_config['mode'] == 'rr_ratio' and stop_loss is not None:
            rr = tp_config.get('rr_ratio', 2.0)
            risk = abs(entry_price - stop_loss)
            if direction == 1:
                return entry_price + (risk * rr)
            else:
                return entry_price - (risk * rr)

        elif tp_config['mode'] == 'fixed':
            fixed = tp_config['fixed_value']
            if direction == 1:
                return entry_price + fixed
            else:
                return entry_price - fixed

        return None

    def update_trailing_stop(self, position: Position,
                            current_price: float) -> Optional[float]:
        """
        Update trailing stop based on current price.

        Args:
            position: Current position
            current_price: Current market price

        Returns:
            New trailing stop price or None if not triggered
        """
        ts_config = self.config['risk']['trailing_stop']

        if not ts_config['enabled']:
            return None

        activation_pct = ts_config['activation'] / 100
        distance_pct = ts_config['distance'] / 100

        if position.direction == 1:  # Long
            # Update highest price
            position.highest_price = max(position.highest_price, current_price)

            # Check if trailing stop should activate
            profit_pct = (position.highest_price - position.entry_price) / position.entry_price
            if profit_pct >= activation_pct:
                new_stop = position.highest_price * (1 - distance_pct)
                if position.trailing_stop_price is None or new_stop > position.trailing_stop_price:
                    return new_stop

        else:  # Short
            # Update lowest price
            position.lowest_price = min(position.lowest_price, current_price)

            # Check if trailing stop should activate
            profit_pct = (position.entry_price - position.lowest_price) / position.entry_price
            if profit_pct >= activation_pct:
                new_stop = position.lowest_price * (1 + distance_pct)
                if position.trailing_stop_price is None or new_stop < position.trailing_stop_price:
                    return new_stop

        return None

    def check_exit(self, position: Position,
                   current_price: float,
                   current_idx: int) -> Optional[str]:
        """
        Check if position should be closed.

        Args:
            position: Current position
            current_price: Current market price
            current_idx: Current index in features

        Returns:
            Exit reason ('tp', 'sl', 'trailing', 'signal') or None
        """
        # Update trailing stop first
        new_trailing = self.update_trailing_stop(position, current_price)
        if new_trailing:
            position.trailing_stop_price = new_trailing

        # Check trailing stop
        if position.trailing_stop_price:
            if position.direction == 1 and current_price <= position.trailing_stop_price:
                return 'trailing'
            if position.direction == -1 and current_price >= position.trailing_stop_price:
                return 'trailing'

        # Check stop loss
        if position.stop_loss:
            if position.direction == 1 and current_price <= position.stop_loss:
                return 'sl'
            if position.direction == -1 and current_price >= position.stop_loss:
                return 'sl'

        # Check take profit
        if position.take_profit:
            if position.direction == 1 and current_price >= position.take_profit:
                return 'tp'
            if position.direction == -1 and current_price <= position.take_profit:
                return 'tp'

        # Check signal reversal
        signal = self.get_signal(current_idx)
        if signal.direction != 0 and signal.direction != position.direction:
            return 'signal'

        return None


# For direct testing
if __name__ == "__main__":
    import yaml

    with open("config.yaml") as f:
        config = yaml.safe_load(f)

    strategy = Strategy(config)
    features = strategy.initialize()

    print(f"Features shape: {features.shape}")
    print(f"Sample signal: {strategy.get_signal(100)}")
